[package]
name = "mmp"
version = "0.1.0"
authors = ["TA Thanh Dinh <tathanhdinh@gmail.com>"]
edition = "2018"

[dependencies]
gio = "^0.5"
gtk = "^0.5"
gtk-sys ="^0.7"
gdk-pixbuf = "^0.5"
id3 = "^0.2"
crossbeam = "^0.5"
pulse-simple = "^1.0"
simplemad = "^0.9"
libc = "^0.2"